# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: etfs
  pool: 5
  username: etf
  password: etfftw
  socket: /tmp/mysql.sock
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: etfs_test
  pool: 5
  username: etf
  password: etfftw
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: etfs
  pool: 5
  username: etfs
  password: etfftw
#  socket: **/opt/local/var/run/mysql5/mysqld.sock**